### ISSUE TITLE
MYMETA must not be included

### ISSUE THREAD

**Issue by chorny** [rvosa/bio-phylo-forest-dbtree#13]
Your distribution (RVOSA/Bio-Phylo-Forest-DBTree-v0.1.2.tar.gz) contains files MYMETA.json/MYMETA.yml. These files must not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is for an old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=RVOSA and contact me.
P.P.S. This report was generated automatically.

**Comment by rvosa** [comment]
Fixed as of https://github.com/rvosa/bio-phylo-forest-dbtree/commit/6b897d724fbbd097902650a86d01cd2b80334816
